require.config({
   paths:{
       jquery:"lib/jquery/dist/jquery",
       bootstrap:"lib/bootstrap/dist/js/bootstrap",
       angular:"lib/angular/angular",
       loadingBar:"lib/angular-loading-bar/src/loading-bar",
       route:"lib/angular-route/angular-route",
       mocks:"lib/angular-mocks/angular-mocks",
       config:"config",
       angucomplete:"lib/angucomplete-alt/angucomplete-alt"
   },
    shim:{
    angular:{
    exports:'angular'
    },
    loadingBar:{
        deps:['angular']
    },
    route:{
        deps:['angular']    
    },
    mocks:{
        deps:['angular']
    },
    config:{
        deps:['route']
    },
    angucomplete:{
        deps:['angular']
     }
}
});

require(["modules/app","config","controllers/movieController","directives/alert","directives/navbar"],function(app){
    app.init();
});
